package CorbaConversion;


/**
* CorbaConversion/IConversionReemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* vendredi 1 décembre 2023 10 h 49 CET
*/

public interface IConversionReemoteOperations 
{
  double conversion (double mt);
} // interface IConversionReemoteOperations
