package CorbaConversion;


/**
* CorbaConversion/IConversionReemotePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* vendredi 1 décembre 2023 11 h 04 CET
*/

public abstract class IConversionReemotePOA extends org.omg.PortableServer.Servant
 implements CorbaConversion.IConversionReemoteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("conversion", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CorbaConversion/IConversionReemote/conversion
       {
         double mt = in.read_double ();
         double $result = (double)0;
         $result = this.conversion (mt);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CorbaConversion/IConversionReemote:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IConversionReemote _this() 
  {
    return IConversionReemoteHelper.narrow(
    super._this_object());
  }

  public IConversionReemote _this(org.omg.CORBA.ORB orb) 
  {
    return IConversionReemoteHelper.narrow(
    super._this_object(orb));
  }


} // class IConversionReemotePOA
