package CorbaConversion;


/**
* CorbaConversion/IConversionReemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* vendredi 1 décembre 2023 11 h 04 CET
*/

public interface IConversionReemote extends IConversionReemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IConversionReemote
