package CorbaConversion;


/**
* CorbaConversion/IConversionReemoteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* vendredi 1 décembre 2023 11 h 04 CET
*/

abstract public class IConversionReemoteHelper
{
  private static String  _id = "IDL:CorbaConversion/IConversionReemote:1.0";

  public static void insert (org.omg.CORBA.Any a, CorbaConversion.IConversionReemote that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CorbaConversion.IConversionReemote extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CorbaConversion.IConversionReemoteHelper.id (), "IConversionReemote");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CorbaConversion.IConversionReemote read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IConversionReemoteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaConversion.IConversionReemote value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CorbaConversion.IConversionReemote narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaConversion.IConversionReemote)
      return (CorbaConversion.IConversionReemote)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaConversion._IConversionReemoteStub stub = new CorbaConversion._IConversionReemoteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CorbaConversion.IConversionReemote unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaConversion.IConversionReemote)
      return (CorbaConversion.IConversionReemote)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaConversion._IConversionReemoteStub stub = new CorbaConversion._IConversionReemoteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
